"""Contacts, staged discovery, and the outreach queue (spec 016).

The staging discipline: discovery writes candidates to a review
artifact; only an explicit approval writes into the contacts store.
"""

from __future__ import annotations

from harrier.outreach.backfill import BackfillSummary, backfill_posters
from harrier.outreach.contacts import (
    best_contact,
    contact_sort_key,
    contacts_for_job,
    delete_contact,
    find_contact,
    infer_relevance,
    parse_linked_jobs,
    serialize_linked_jobs,
    update_contact,
    update_contact_status,
    upsert_contact,
)
from harrier.outreach.discovery import (
    approve_candidate,
    build_best_contact_search_specs,
    build_search_specs,
    find_best_contacts_for_job,
    find_contacts_for_job,
    has_strong_best_contact,
    load_candidates_artifact,
    merge_ranked_contacts,
    normalize_profile_result,
    outreach_slug,
    score_contact_fit,
    update_candidate_review_status,
    write_candidates_artifact,
)
from harrier.outreach.drafts import (
    generate_ai_outreach,
    generate_outreach,
    infer_audience,
    parse_ai_outreach_response,
    render_outreach_markdown,
    write_outreach_draft,
)
from harrier.outreach.hunter import domain_search, find_email, verify_email
from harrier.outreach.messages import (
    MESSAGE_KINDS,
    MessageVariant,
    OutreachRequest,
    check_message,
    generate_message_bundle,
    load_configs,
    rewrite_message,
    save_generated_bundle,
    save_target,
)
from harrier.outreach.state import (
    business_days_after,
    filter_outreach_rows,
    mark_job_outreach_replied,
    mark_job_outreach_sent,
    outreach_due_rows,
    refresh_outreach_fields,
    set_best_contact_for_job,
    snooze_job_outreach,
    sync_tracker_outreach,
)

__all__ = [
    "MESSAGE_KINDS",
    "BackfillSummary",
    "MessageVariant",
    "OutreachRequest",
    "approve_candidate",
    "backfill_posters",
    "best_contact",
    "build_best_contact_search_specs",
    "build_search_specs",
    "business_days_after",
    "check_message",
    "contact_sort_key",
    "contacts_for_job",
    "delete_contact",
    "domain_search",
    "filter_outreach_rows",
    "find_best_contacts_for_job",
    "find_contact",
    "find_contacts_for_job",
    "find_email",
    "generate_ai_outreach",
    "generate_message_bundle",
    "generate_outreach",
    "has_strong_best_contact",
    "infer_audience",
    "infer_relevance",
    "load_candidates_artifact",
    "load_configs",
    "mark_job_outreach_replied",
    "mark_job_outreach_sent",
    "merge_ranked_contacts",
    "normalize_profile_result",
    "outreach_due_rows",
    "outreach_slug",
    "parse_ai_outreach_response",
    "parse_linked_jobs",
    "refresh_outreach_fields",
    "render_outreach_markdown",
    "rewrite_message",
    "save_generated_bundle",
    "save_target",
    "score_contact_fit",
    "serialize_linked_jobs",
    "set_best_contact_for_job",
    "snooze_job_outreach",
    "sync_tracker_outreach",
    "update_candidate_review_status",
    "update_contact",
    "update_contact_status",
    "upsert_contact",
    "verify_email",
    "write_candidates_artifact",
    "write_outreach_draft",
]
