/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/apply/{selector}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft Answers */
        post: operations["draftAnswers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apply/{selector}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Artifacts
         * @description The index requires the token even though it is a read.
         *
         *     Tracker reads do not, and this deliberately differs: the names here are
         *     derived from the candidate's own name and the company, and the bodies
         *     behind them are the densest personal content the system holds (spec 047).
         */
        get: operations["listArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apply/{selector}/artifacts/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Artifact */
        get: operations["readArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apply/{selector}/cover-letter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft Cover Letter */
        post: operations["draftCoverLetter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apply/{selector}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Offer Route */
        post: operations["evaluateOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apply/{selector}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tailor Resume
         * @description The same `tailor` verb the CLI runs, as a run (spec 047).
         */
        post: operations["tailorResume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capture/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capture Confirm
         * @description Renders. Changes nothing.
         *
         *     This used to add the row, which meant `<img src="http://localhost:8000/
         *     capture/add?company=x&title=y">` on any page the operator visited wrote to
         *     the tracker with no interaction at all (spec 035).
         */
        get: operations["captureJobConfirm"];
        put?: never;
        /** Capture Via Post */
        post: operations["captureJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capture/add-form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Capture From Form
         * @description The confirmation page's submit target.
         *
         *     A form post cannot set a header, so the token travels as a field. A
         *     cross-origin page can post a form here, but it cannot read the token, so
         *     it cannot fill that field.
         */
        post: operations["captureJobFromForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Configuration */
        get: operations["listConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Configuration */
        get: operations["getConfig"];
        /** Put Configuration */
        put: operations["putConfig"];
        post?: never;
        /**
         * Delete Configuration
         * @description Remove a stored value, restoring the file fallback.
         */
        delete: operations["deleteConfig"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outreach/backfill-posters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Backfill
         * @description Acts on every LinkedIn row rather than one job, so it takes no
         *     selector and locks one at a time, as discovery does.
         */
        post: operations["backfillPosters"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outreach/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Outreach Contacts */
        get: operations["listOutreachContacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outreach/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Outreach Due */
        get: operations["listOutreachDue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outreach/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Outreach */
        post: operations["syncOutreach"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outreach/{selector}/best-contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Best Contact */
        post: operations["setBestContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outreach/{selector}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Candidates
         * @description The staged artifact, read through the same extraction approve uses.
         *
         *     This carries a real person's name and title, so it authenticates, for the
         *     same reason spec 047's artifact reads do.
         */
        get: operations["listCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outreach/{selector}/candidates/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve
         * @description The only path in this API from a staged candidate to a stored contact.
         *
         *     A candidate discovery never staged is refused rather than created, which
         *     is the staging invariant holding at the one place it could be bypassed.
         */
        post: operations["approveCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outreach/{selector}/candidates/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["rejectCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outreach/{selector}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Draft Outreach
         * @description The contact and the tone travel in a file, not argv.
         *
         *     A contact's name and LinkedIn URL are a real person's details, and argv
         *     is readable from the process table by every other process on the machine
         *     (spec 047's rule, applied to spec 048's inputs).
         */
        post: operations["draftOutreach"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outreach/{selector}/find-contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Find Contacts
         * @description A run, and one that spends money: it reaches Hunter and Apify.
         *
         *     It stages candidates. It writes no contact, which is the invariant this
         *     module exists to keep.
         */
        post: operations["findContacts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outreach/{selector}/replied": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Replied */
        post: operations["markOutreachReplied"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outreach/{selector}/sent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Sent
         * @description Records that the operator sent something themselves.
         *
         *     It sends nothing. The page says so in those words, because a control
         *     next to a generated draft is exactly where that would be misread.
         */
        post: operations["markOutreachSent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outreach/{selector}/snooze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snooze */
        post: operations["snoozeOutreach"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["listRuns"];
        put?: never;
        /** Start Run */
        post: operations["startRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run Events */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description The local API token, for the app this API serves.
         *
         *     A cross-origin page may issue this request but cannot read the response:
         *     no CORS headers are sent, so the browser withholds the body. A page that
         *     made itself same-origin by DNS rebinding could read it, which is what the
         *     trusted-host middleware exists to prevent, and why that middleware is the
         *     load-bearing half of this pair rather than the token.
         */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Job By Hand */
        post: operations["addJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracker/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tracker Counts */
        get: operations["trackerCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracker/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Queue
         * @description `next` and `review`, which are the same ranking over different
         *     statuses: `next` is everything active, `review` narrows to what still
         *     needs a decision from the operator.
         */
        get: operations["listQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracker/{selector}/rescore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rescore Job */
        post: operations["rescoreJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracker/{selector}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Job Status
         * @description The same function the CLI's shortlist, track, applied, interviewing
         *     and reject verbs call (spec 042).
         */
        post: operations["changeJobStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddJobIn */
        AddJobIn: {
            /** Company */
            company: string;
            /**
             * Description
             * @default
             */
            description?: string;
            /**
             * Location
             * @default
             */
            location?: string;
            /**
             * Source
             * @default manual
             */
            source?: string;
            /** Title */
            title: string;
            /**
             * Url
             * @default
             */
            url?: string;
        };
        /** AddJobOut */
        AddJobOut: {
            job?: components["schemas"]["JobOut"] | null;
            /** Message */
            message: string;
            /** Status */
            status: string;
        };
        /** AnswersIn */
        AnswersIn: {
            /**
             * Questions
             * @default
             */
            questions?: string;
        };
        /**
         * ArtifactOut
         * @description One artifact kind for a job, present or not.
         *
         *     Carries the filename rather than the path: the operator does not need the
         *     absolute location, and it would put the home directory into every
         *     response for nothing.
         */
        ArtifactOut: {
            /** Exists */
            exists: boolean;
            /** Filename */
            filename: string;
            /** Kind */
            kind: string;
            /** Media Type */
            media_type: string;
            /** Produced By */
            produced_by: string;
        };
        /** BackfillIn */
        BackfillIn: {
            /**
             * Dry Run
             * @default false
             */
            dry_run?: boolean;
            /** Limit */
            limit?: number | null;
        };
        /** Body_captureJobFromForm */
        Body_captureJobFromForm: {
            /**
             * Company
             * @default
             */
            company?: string;
            /**
             * Description
             * @default
             */
            description?: string;
            /**
             * Location
             * @default
             */
            location?: string;
            /**
             * Source
             * @default manual
             */
            source?: string;
            /**
             * Title
             * @default
             */
            title?: string;
            /**
             * Token
             * @default
             */
            token?: string;
            /**
             * Url
             * @default
             */
            url?: string;
        };
        /** CandidateOut */
        CandidateOut: {
            /** Fit Score */
            fit_score: string;
            /** Linkedin Url */
            linkedin_url: string;
            /** Person Name */
            person_name: string;
            /** Person Title */
            person_title: string;
            /** Relevance */
            relevance: string;
            /** Review Status */
            review_status: string;
        };
        /**
         * CandidateRef
         * @description A staged candidate, identified the way the CLI identifies one.
         */
        CandidateRef: {
            /** Linkedin Url */
            linkedin_url: string;
        };
        /** CaptureIn */
        CaptureIn: {
            /**
             * Company
             * @default
             */
            company?: string;
            /**
             * Description
             * @default
             */
            description?: string;
            /**
             * Location
             * @default
             */
            location?: string;
            /**
             * Source
             * @default manual
             */
            source?: string;
            /**
             * Title
             * @default
             */
            title?: string;
            /**
             * Url
             * @default
             */
            url?: string;
        };
        /** CaptureOut */
        CaptureOut: {
            /** Message */
            message: string;
            /** Ok */
            ok: boolean;
        };
        /**
         * ConfigErrorOut
         * @description The body behind a 404 or a 400 on these routes.
         *
         *     Declared so the generated client knows these outcomes exist. Store
         *     validation answers 400 rather than 422 on purpose: FastAPI already owns
         *     422 for a malformed request body, where the detail is a list of field
         *     errors. Reusing it would have put two different shapes behind one status
         *     and hidden the automatic one from the contract entirely (review finding
         *     on PR #20). A well-formed ConfigIn whose value is wrong for its kind is
         *     a different failure, and says so with a different code.
         */
        ConfigErrorOut: {
            /** Detail */
            detail: string;
        };
        /** ConfigIn */
        ConfigIn: {
            /** Value */
            value: unknown;
        };
        /**
         * ConfigOut
         * @description One configuration kind and where its current value comes from.
         *
         *     `source` is the point of this endpoint: a reader has to be able to tell
         *     a value someone set from a value that is still coming out of a file,
         *     because unsetting the first restores the second (spec 023).
         */
        ConfigOut: {
            /** Kind */
            kind: string;
            /**
             * Source
             * @enum {string}
             */
            source: "store" | "file";
            /** Updated At */
            updated_at: string | null;
            /** Value */
            value: unknown;
        };
        /** ContactOut */
        ContactOut: {
            /** Company */
            company: string;
            /** Contact Status */
            contact_status: string;
            /** Id */
            id: number;
            /** Linkedin Url */
            linkedin_url: string;
            /** Person Name */
            person_name: string;
            /** Person Title */
            person_title: string;
            /** Relevance */
            relevance: string;
        };
        /** CoverLetterIn */
        CoverLetterIn: {
            /**
             * Notes
             * @default
             */
            notes?: string;
        };
        /** DraftIn */
        DraftIn: {
            /**
             * Ai
             * @default false
             */
            ai?: boolean;
            /**
             * Audience
             * @default
             */
            audience?: string;
            /**
             * Contact Linkedin
             * @default
             */
            contact_linkedin?: string;
            /**
             * Contact Name
             * @default
             */
            contact_name?: string;
            /**
             * Contact Role
             * @default
             */
            contact_role?: string;
            /**
             * Jd Text
             * @default
             */
            jd_text?: string;
            /**
             * Tone
             * @default direct
             */
            tone?: string;
        };
        /** EvaluateIn */
        EvaluateIn: {
            /**
             * Jd Text
             * @default
             */
            jd_text?: string;
        };
        /** FindContactsIn */
        FindContactsIn: {
            /**
             * Best Only
             * @default false
             */
            best_only?: boolean;
            /** Max Items */
            max_items?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Database */
            database: string;
            /** Demo */
            demo: boolean;
            /** Job Count */
            job_count: number;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** JobOut */
        JobOut: {
            /** Added At */
            added_at: string;
            /** Applied Date */
            applied_date: string;
            /** Archetype */
            archetype: string;
            /** Best Contact Linkedin */
            best_contact_linkedin: string;
            /** Best Contact Name */
            best_contact_name: string;
            /** Company */
            company: string;
            /** Contacts Found */
            contacts_found: string;
            /** Created At */
            created_at: string;
            /** External Key */
            external_key: string;
            /** Fit Score */
            fit_score: string;
            /** Id */
            id: number;
            /** Last Contact */
            last_contact: string;
            /** Last Outreach At */
            last_outreach_at: string;
            /** Location */
            location: string;
            /** Manual Added */
            manual_added: string;
            /** Next Action */
            next_action: string;
            /** Next Outreach Action */
            next_outreach_action: string;
            /** Notes */
            notes: string;
            /** Outreach Priority */
            outreach_priority: string;
            /** Outreach Status */
            outreach_status: string;
            /** Rejection Reason */
            rejection_reason: string;
            /** Remote Filter */
            remote_filter: string;
            /** Score */
            score: string;
            /** Signals */
            signals: string;
            /** Source */
            source: string;
            /** Source Label */
            source_label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "prospect" | "shortlisted" | "tailored_cv_requested" | "applied" | "interviewing" | "rejected";
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
            /** Url */
            url: string;
        };
        /** MarkIn */
        MarkIn: {
            /** Date */
            date?: string | null;
        };
        /**
         * OutreachRowOut
         * @description A tracker row seen through the outreach axis, which is orthogonal to
         *     the status lifecycle and stays that way.
         */
        OutreachRowOut: {
            /** Best Contact Linkedin */
            best_contact_linkedin: string;
            /** Best Contact Name */
            best_contact_name: string;
            /** Company */
            company: string;
            /** Id */
            id: number;
            /** Next Outreach Action */
            next_outreach_action: string;
            /** Outreach Status */
            outreach_status: string;
            /** Title */
            title: string;
        };
        /** RescoreOut */
        RescoreOut: {
            /** Current */
            current: number;
            job: components["schemas"]["JobOut"];
            /** Previous */
            previous: string;
        };
        /**
         * RunEventOut
         * @description The JSON payload of one SSE message on /runs/{id}/events.
         *
         *     Declared on the route's response documentation so it lands in the OpenAPI
         *     components and the web app consumes the generated type (spec 006). The
         *     stream itself is text/event-stream; each message's data field is one of
         *     these, flattened per event type: log_line carries line, progress carries
         *     step/total/message, state_change carries state/exit_code.
         */
        RunEventOut: {
            /** Exit Code */
            exit_code?: number | null;
            /** Line */
            line?: string | null;
            /** Message */
            message?: string | null;
            /** State */
            state?: ("queued" | "running" | "succeeded" | "failed" | "cancelled" | "interrupted") | null;
            /** Step */
            step?: number | null;
            /** Total */
            total?: number | null;
            /** Type */
            type: string;
        };
        /** RunOut */
        RunOut: {
            /** Created At */
            created_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Exit Code */
            exit_code: number | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Started At */
            started_at: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "interrupted";
        };
        /** SessionOut */
        SessionOut: {
            /** Token */
            token: string;
        };
        /** SnoozeIn */
        SnoozeIn: {
            /** Until */
            until: string;
        };
        /** StartRunIn */
        StartRunIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "demo" | "discovery";
        };
        /** StatusChangeIn */
        StatusChangeIn: {
            /** Reason */
            reason?: string | null;
            /** Verb */
            verb: string;
        };
        /** TailorIn */
        TailorIn: {
            /**
             * Jd Text
             * @default
             */
            jd_text?: string;
            /**
             * No Ai
             * @default false
             */
            no_ai?: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    draftAnswers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswersIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no job matched the selector */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactOut"][];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no job matched the selector */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no such job, artifact kind, or the artifact is not produced yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draftCoverLetter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoverLetterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no job matched the selector */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluateOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no job matched the selector */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tailorResume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TailorIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no job matched the selector */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    captureJobConfirm: {
        parameters: {
            query?: {
                company?: string;
                title?: string;
                location?: string;
                url?: string;
                source?: string;
                description?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description confirmation page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    captureJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureOut"];
                };
            };
            /** @description company and title are required */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description already in tracker */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    captureJobFromForm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_captureJobFromForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description company and title are required */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description missing or wrong local token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description already in tracker */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"][];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
            /** @description No such configuration kind. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    putConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
            /** @description The value is not the shape this kind requires. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigErrorOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such configuration kind. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such configuration kind. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    listJobs: {
        parameters: {
            query?: {
                status?: ("prospect" | "shortlisted" | "tailored_cv_requested" | "applied" | "interviewing" | "rejected") | null;
                source?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backfillPosters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackfillIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listOutreachContacts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"][];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listOutreachDue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutreachRowOut"][];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    syncOutreach: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutreachRowOut"][];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setBestContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateRef"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutreachRowOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no job matched the selector, or the candidate was never staged */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the domain refused the change */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listCandidates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"][];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no job matched the selector, or the candidate was never staged */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the domain refused the change */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approveCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateRef"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no job matched the selector, or the candidate was never staged */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the domain refused the change */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rejectCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateRef"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no job matched the selector, or the candidate was never staged */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the domain refused the change */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draftOutreach: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no job matched the selector, or the candidate was never staged */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the domain refused the change */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    findContacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindContactsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no job matched the selector, or the candidate was never staged */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the domain refused the change */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    markOutreachReplied: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutreachRowOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no job matched the selector, or the candidate was never staged */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the domain refused the change */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    markOutreachSent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutreachRowOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no job matched the selector, or the candidate was never staged */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the domain refused the change */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snoozeOutreach: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnoozeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutreachRowOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no job matched the selector, or the candidate was never staged */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the domain refused the change */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
        };
    };
    startRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream; each message's data field is a RunEventOut JSON payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    addJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddJobIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddJobOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trackerCounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    listQueue: {
        parameters: {
            query?: {
                undecided?: boolean;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescoreJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RescoreOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no job matched the selector */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the tracker refused the change */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    changeJobStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                selector: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description missing or wrong local API token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no job matched the selector */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the tracker refused the change */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
