/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Database */
            database: string;
            /** Demo */
            demo: boolean;
            /** Job Count */
            job_count: number;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** JobOut */
        JobOut: {
            /** Added At */
            added_at: string;
            /** Applied Date */
            applied_date: string;
            /** Archetype */
            archetype: string;
            /** Best Contact Linkedin */
            best_contact_linkedin: string;
            /** Best Contact Name */
            best_contact_name: string;
            /** Company */
            company: string;
            /** Contacts Found */
            contacts_found: string;
            /** Created At */
            created_at: string;
            /** External Key */
            external_key: string;
            /** Fit Score */
            fit_score: string;
            /** Id */
            id: number;
            /** Last Contact */
            last_contact: string;
            /** Last Outreach At */
            last_outreach_at: string;
            /** Location */
            location: string;
            /** Manual Added */
            manual_added: string;
            /** Manual Reject */
            manual_reject: string;
            /** Next Action */
            next_action: string;
            /** Next Outreach Action */
            next_outreach_action: string;
            /** Notes */
            notes: string;
            /** Outreach Priority */
            outreach_priority: string;
            /** Outreach Status */
            outreach_status: string;
            /** Rejection Reason */
            rejection_reason: string;
            /** Remote Filter */
            remote_filter: string;
            /** Score */
            score: string;
            /** Signals */
            signals: string;
            /** Source */
            source: string;
            /** Source Label */
            source_label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "prospect" | "shortlisted" | "tailored_cv_requested" | "applied" | "interviewing" | "rejected";
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
            /** Url */
            url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    listJobs: {
        parameters: {
            query?: {
                status?: ("prospect" | "shortlisted" | "tailored_cv_requested" | "applied" | "interviewing" | "rejected") | null;
                source?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
