/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/capture/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capture Via Get */
        get: operations["captureJobViaGet"];
        put?: never;
        /** Capture Via Post */
        post: operations["captureJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["listRuns"];
        put?: never;
        /** Start Run */
        post: operations["startRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run Events */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CaptureIn */
        CaptureIn: {
            /**
             * Company
             * @default
             */
            company: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Source
             * @default manual
             */
            source: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Url
             * @default
             */
            url: string;
        };
        /** CaptureOut */
        CaptureOut: {
            /** Message */
            message: string;
            /** Ok */
            ok: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Database */
            database: string;
            /** Demo */
            demo: boolean;
            /** Job Count */
            job_count: number;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** JobOut */
        JobOut: {
            /** Added At */
            added_at: string;
            /** Applied Date */
            applied_date: string;
            /** Archetype */
            archetype: string;
            /** Best Contact Linkedin */
            best_contact_linkedin: string;
            /** Best Contact Name */
            best_contact_name: string;
            /** Company */
            company: string;
            /** Contacts Found */
            contacts_found: string;
            /** Created At */
            created_at: string;
            /** External Key */
            external_key: string;
            /** Fit Score */
            fit_score: string;
            /** Id */
            id: number;
            /** Last Contact */
            last_contact: string;
            /** Last Outreach At */
            last_outreach_at: string;
            /** Location */
            location: string;
            /** Manual Added */
            manual_added: string;
            /** Manual Reject */
            manual_reject: string;
            /** Next Action */
            next_action: string;
            /** Next Outreach Action */
            next_outreach_action: string;
            /** Notes */
            notes: string;
            /** Outreach Priority */
            outreach_priority: string;
            /** Outreach Status */
            outreach_status: string;
            /** Rejection Reason */
            rejection_reason: string;
            /** Remote Filter */
            remote_filter: string;
            /** Score */
            score: string;
            /** Signals */
            signals: string;
            /** Source */
            source: string;
            /** Source Label */
            source_label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "prospect" | "shortlisted" | "tailored_cv_requested" | "applied" | "interviewing" | "rejected";
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
            /** Url */
            url: string;
        };
        /**
         * RunEventOut
         * @description The JSON payload of one SSE message on /runs/{id}/events.
         *
         *     Declared on the route's response documentation so it lands in the OpenAPI
         *     components and the web app consumes the generated type (spec 006). The
         *     stream itself is text/event-stream; each message's data field is one of
         *     these, flattened per event type: log_line carries line, progress carries
         *     step/total/message, state_change carries state/exit_code.
         */
        RunEventOut: {
            /** Exit Code */
            exit_code?: number | null;
            /** Line */
            line?: string | null;
            /** Message */
            message?: string | null;
            /** State */
            state?: ("queued" | "running" | "succeeded" | "failed" | "cancelled") | null;
            /** Step */
            step?: number | null;
            /** Total */
            total?: number | null;
            /** Type */
            type: string;
        };
        /** RunOut */
        RunOut: {
            /** Created At */
            created_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Exit Code */
            exit_code: number | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Started At */
            started_at: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        };
        /** StartRunIn */
        StartRunIn: {
            /**
             * Kind
             * @constant
             */
            kind: "demo";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    captureJobViaGet: {
        parameters: {
            query?: {
                company?: string;
                title?: string;
                location?: string;
                url?: string;
                source?: string;
                description?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    captureJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureOut"];
                };
            };
            /** @description company and title are required */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureOut"];
                };
            };
            /** @description already in tracker */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    listJobs: {
        parameters: {
            query?: {
                status?: ("prospect" | "shortlisted" | "tailored_cv_requested" | "applied" | "interviewing" | "rejected") | null;
                source?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
        };
    };
    startRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream; each message's data field is a RunEventOut JSON payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
